In [2]:
pip install NumPy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 3.7 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

NumPy Arrays

A grid of values, all of the same type.

Rank: number of dimensions of the array

Shape: an array of tuple of integers giving the size of the array along each dimension.

In [4]:
# Rank 1 array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
print(type(a))  # Output: (3,)

<class 'numpy.ndarray'>


In [10]:
print(a.shape)

(3,)


In [13]:
# Accessing the first element of the array
print(a[0])

1


In [ ]:
a[0] = 5 # Modifying the first element
print(a)

[5 2 3]


In [15]:
#Rank 2 array
b = np.array([[1, 2, 3],
             [4, 5, 6]])

print(b)

[[1 2 3]
 [4 5 6]]


In [17]:
print(b.shape)  # Output: (3,)

(2, 3)


In [19]:
print(b[0,0])
b[1,2] = 10
print(b)

1
[[ 1  2  3]
 [ 4  5 10]]


Special Arrays

In [22]:
a = np.zeros((3, 6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
b = np.array([[1,2,3], [3,4,5]])

np.zeros_like(b, dtype=float)


array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
b = np.ones((3, 6))
print(b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [29]:
c = np.full((3, 6), 3)
print(c)

[[3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]]


In [31]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
e = np.random.random((3,3))
print(e)

[[0.21462079 0.66369102 0.42959292]
 [0.4296414  0.43617947 0.57015573]
 [0.60108236 0.66850285 0.36598069]]


Indexing

In [36]:
a = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12],
              [1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
a[1:4, 1:4]  # Accessing the first two rows and columns

array([[ 6,  7,  8],
       [10, 11, 12],
       [ 2,  3,  4]])

In [41]:
print(a.shape)  # Output: (3,)

(6, 4)


In [61]:
a[1, :]

array([5, 6, 7, 8])

In [60]:
a[:, 0:1]  # Accessing the first column

array([[1],
       [5],
       [9],
       [1],
       [5],
       [9]])

In [52]:
np.arange(2,10,2) # (start, end+1, step)

array([2, 4, 6, 8])

In [54]:
bool_idx = (a > 10)
print(a[bool_idx])  # Accessing elements greater than 10

[11 12 11 12]


In [55]:
a[a>10]

array([11, 12, 11, 12])

Data Type

In [62]:
x = np.array([1,2])
print(x.dtype)

int64


In [63]:
x = np.array([1.0, 2.1])
print(x.dtype)

float64


In [65]:
x = np.array([1,2], dtype=np.float64) 
print(x.dtype)

float64


Operations

In [66]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [67]:
print(x+y)

[[ 6  8]
 [10 12]]


In [68]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [69]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [70]:
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [72]:
print(x*y)

[[ 5 12]
 [21 32]]


In [73]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [74]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [75]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [76]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [77]:
print(x.dot(y)) # Dot product of two arrays

[[19 22]
 [43 50]]


In [78]:
print(np.dot(x,y)) # Dot product using numpy function

[[19 22]
 [43 50]]


In [79]:
np.sum(x) # Sum of all elements in x

np.int64(10)

In [80]:
np.sum(x, axis=0) # Sum along the first axis (columns)

array([4, 6])

In [81]:
np.sum(x, axis=1) # Sum along the second axis (rows)

array([3, 7])

In [83]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
a.T # Transpose of the array

array([[ 1,  5,  9,  1,  5,  9],
       [ 2,  6, 10,  2,  6, 10],
       [ 3,  7, 11,  3,  7, 11],
       [ 4,  8, 12,  4,  8, 12]])

In [84]:
a.shape

(6, 4)

Broadcasting

In [85]:
x = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])
v = np.array([1, 2])

y = x + v  # Broadcasting

print(y) # Each row of x is added to v

[[2 4]
 [4 6]
 [6 8]]


In [87]:
x.T

array([[1, 3, 5],
       [2, 4, 6]])